CREATE TABLE LIST_EXAMPLE
    ( state_cd varchar2(2), data varchar2(20))
PARTITION BY LIST(state_cd)
    ( partition part_1 values ( 'ME', 'NH', 'VT', 'MA' ),
partition part_2 values ( 'CT', 'RI', 'NY' )
    )
/

INSERT INTO LIST_EXAMPLE VALUES ( 'CT', 'data' );
INSERT INTO LIST_EXAMPLE VALUES ( 'MA', 'data' );
INSERT INTO LIST_EXAMPLE VALUES ( 'ME', 'data' );
INSERT INTO LIST_EXAMPLE VALUES ( 'NH', 'data' );
INSERT INTO LIST_EXAMPLE VALUES ( 'NY', 'data' );
INSERT INTO LIST_EXAMPLE VALUES ( 'RI', 'data' );
INSERT INTO LIST_EXAMPLE VALUES ( 'VT', 'data' );

SELECT state_cd FROM LIST_EXAMPLE partition (part_1);
SELECT state_cd FROM LIST_EXAMPLE partition (part_2);

 -- ADD PARTITION
ALTER TABLE LIST_EXAMPLE
 ADD PARTITION part_3 values ( DEFAULT );
 
INSERT INTO LIST_EXAMPLE VALUES( 'VA', 'data' );
SELECT state_cd FROM LIST_EXAMPLE partition (part_3);
 
 -- DROP PARTITION
ALTER TABLE LIST_EXAMPLE DROP PARTITION part_3;
      
-- MERGE PARTITION
ALTER TABLE LIST_EXAMPLE
    ADD PARTITION part_3 values ( 'LA', 'TX' );
 
ALTER TABLE LIST_EXAMPLE
    ADD PARTITION part_4 values ( 'AB', 'BC', 'CD' );

ALTER TABLE LIST_EXAMPLE
    MERGE PARTITIONS part_3, part_4 INTO PARTITION part_3;
    

 -- MOVE PARTITION
ALTER TABLE LIST_EXAMPLE
    MOVE PARTITION part_3 TABLESPACE ts_stuff;


-- SPLIT PARTITION
ALTER TABLE LIST_EXAMPLE
    SPLIT PARTITION part_3 INTO 
      (PARTITION part_3 values ( 'LA', 'TX' ), PARTITION part_4);
   

 -- TRUNCATE PARTITION
ALTER TABLE LIST_EXAMPLE TRUNCATE PARTITION part_4;
 
DROP TABLE LIST_EXAMPLE;