alter session set current_schema = DW_DATA;

CREATE TABLE DIM_SHOWING(
    SHOWING_ID NUMBER NOT NULL,
    THEATER_ID NUMBER NOT NULL,
    MOVIE_ID NUMBER NOT NULL,
    SHOWING_TYPE        VARCHAR2(10),
    SHOWING_CAPACITY      NUMBER,
    TICKET_PRICE NUMBER NOT NULL,
    CONSTRAINT "PK_T.DIM_SHOWING" PRIMARY KEY(SHOWING_ID) 
);

CREATE SEQUENCE SEQ_SHOWINGS
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 

 
select * from DIM_SHOWING;