alter session set current_schema = DW_DATA;

--DROP TABLE DIM_CURRENCY CASCADE CONSTRAINTS;

CREATE TABLE DIM_CURRENCY(
    CURRENCY_ID NUMBER NOT NULL, 
    CURRENCY_NAME VARCHAR(20) NOT NULL,
    CURRENCY_COUNTRY_CODE VARCHAR2(10) NOT NULL,
    EXCHANGE_RATE  DECIMAL(5,2) NOT NULL,
    CONSTRAINT "PK_T.DIM_CURRENCY" PRIMARY KEY(CURRENCY_ID) 
);

--DROP SEQUENCE SEQ_CURRENCY;
CREATE SEQUENCE SEQ_CURRENCY
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

select * from DIM_CURRENCY