alter session set current_schema = DM_MARKETING;

drop view DM_MARKETING.V_MARKETING;

CREATE OR REPLACE VIEW DM_MARKETING.V_MARKETING AS
SELECT  fct.ATTENDANCE_ID, 
        fct.TRANSACTION_DATE,
        fct.COUNTRY_CODE,
        mov.MOVIE_NAME,
        fct.SOLD_TICKETS,
        fct.PROMOTION_ID
  FROM (SELECT DISTINCT * FROM DW_DATA.FCT_ATTENDANCE) fct
  LEFT JOIN DW_DATA.DIM_MOVIE mov ON (fct.MOVIE_ID = mov.MOVIE_ID);

alter session set current_schema = DW_DATA;
GRANT DELETE,INSERT,UPDATE,SELECT on FCT_ATTENDANCE TO DM_MARKETING;
GRANT DELETE,INSERT,UPDATE,SELECT on DIM_MOVIE TO DM_MARKETING;
GRANT DELETE,INSERT,UPDATE,SELECT on DIM_PROMOTION TO DM_MARKETING;


select * from DM_MARKETING.V_MARKETING order by 2;
select count(*) from DM_WORKLOAD.V_MARKETING;


CREATE OR REPLACE VIEW DM_MARKETING.V_MOVIE AS
SELECT  * FROM DW_DATA.DIM_MOVIE;
  
select * from DM_MARKETING.V_MOVIE;

CREATE OR REPLACE VIEW DM_MARKETING.V_PROMOTION AS
SELECT  * FROM DW_DATA.DIM_PROMOTION;

select * from DM_MARKETING.V_PROMOTION;