alter session set current_schema = DM_WORKLOAD;

drop view DM_WORKLOAD.V_ATTENDANCE;

CREATE OR REPLACE VIEW DM_WORKLOAD.V_ATTENDANCE AS
SELECT  fct.ATTENDANCE_ID, 
        fct.TRANSACTION_DATE,
        sh.SHOWING_TYPE,
        fct.COUNTRY_CODE,
        th.THEATER_NAME,
        fct.SOLD_TICKETS
  FROM (SELECT DISTINCT * FROM DW_DATA.FCT_ATTENDANCE) fct
  LEFT JOIN DW_DATA.DIM_THEATER th ON (th.THEATER_ID = fct.THEATER_ID)
  LEFT JOIN DW_DATA.DIM_SHOWING sh ON (sh.SHOWING_ID = fct.SHOWING_ID);

alter session set current_schema = DW_DATA;
GRANT DELETE,INSERT,UPDATE,SELECT on FCT_ATTENDANCE TO DM_WORKLOAD;
GRANT DELETE,INSERT,UPDATE,SELECT on DIM_THEATER TO DM_WORKLOAD;
GRANT DELETE,INSERT,UPDATE,SELECT on DIM_SHOWING TO DM_WORKLOAD;


select * from DM_WORKLOAD.V_ATTENDANCE order by 2;
select count(*) from DM_WORKLOAD.V_ATTENDANCE;


CREATE OR REPLACE VIEW DM_WORKLOAD.V_THEATER AS
SELECT  THEATER_ID, 
        COUNTRY_CODE,
        CITY,
        THEATER_NAME,
        THEATER_ADDRESS,
        THEATER_PHONE
  FROM DW_DATA.DIM_THEATER;
  
select * from DM_WORKLOAD.V_THEATER;