ALTER USER SA_PROMOTION_DATA quota unlimited on ts_sa_promotion_data_01;
alter session set current_schema = SA_PROMOTION_DATA;

drop table SA_T_PROMOTIONS;

CREATE TABLE SA_T_PROMOTIONS(
    PROMOTION_ID NUMBER,    
    DISCOUNT DECIMAL(3,2)
);

INSERT INTO SA_T_PROMOTIONS (
SELECT rownum AS  PROMOTION_ID, TRUNC(DBMS_RANDOM.VALUE(0, 0.5),2) as DISCOUNT
FROM dual
CONNECT BY level <= 100
);

SELECT * FROM SA_T_PROMOTIONS;
SELECT COUNT(*) FROM SA_T_PROMOTIONS;

GRANT SELECT ON SA_T_PROMOTIONS TO SA_THEATER_DATA;
GRANT SELECT ON SA_T_PROMOTIONS TO DW_CL;