alter session set current_schema = DW_CL;

 DROP TABLE CLS_T_PROMOTIONS;

CREATE TABLE CLS_T_PROMOTIONS(
    PROMOTION_NUM NUMBER,
    DISCOUNT DECIMAL(3,2)
);

GRANT SELECT ON DW_CL.CLS_T_PROMOTIONS TO DW_DATA;


CREATE SEQUENCE SEQ_PROM_NUM
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 SELECT * FROM CLS_T_PROMOTIONS;