alter session set current_schema = DW_CL;

-- DROP TABLE CLS_T_SHOWINGS;

CREATE TABLE CLS_T_SHOWINGS(    
    THEATER_ID NUMBER,
    MOVIE_ID NUMBER,
    SHOWING_TYPE VARCHAR2(10),
    SHOWING_CAPACITY NUMBER,
    TICKET_PRICE NUMBER
);