alter session set current_schema = DW_CL;

DROP TABLE CLS_T_PROMOTIONS;

CREATE TABLE CLS_T_PROMOTIONS(
    PROMOTION_NUM NUMBER,
    DISCOUNT DECIMAL(3,2),
    VALID_FROM DATE,
    VALID_TO DATE,
    IS_ACTIVE CHAR(1) CHECK (IS_ACTIVE IN ('Y','N'))
);

GRANT SELECT ON DW_CL.CLS_T_PROMOTIONS TO DW_DATA;



 SELECT * FROM CLS_T_PROMOTIONS;
 
