alter session set current_schema = DW_CL;

--DROP TABLE CLS_T_MOVIE;

CREATE TABLE CLS_T_MOVIE(  
    MOVIE_NAME VARCHAR2 (100),
    MOVIE_YEAR VARCHAR2(4),
    MOVIE_LEVEL1 VARCHAR2(50),
    MOVIE_LEVEL2 VARCHAR2(50),
    MOVIE_LEVEL3 VARCHAR2(50),
    MOVIE_DURATION NUMBER
);