alter session set current_schema = DW_CL;

-- DROP TABLE cls_t_theaters;

CREATE TABLE CLS_T_THEATERS(
    COUNTRY_CODE VARCHAR2 (10),
    CITY VARCHAR2 (50),
    THEATER_NAME VARCHAR2 (100),
    THEATER_ADDRESS VARCHAR2(100),
    THEATER_PHONE VARCHAR2(15)
);