ALTER USER  SA_CURRENCIES_DATA quota unlimited on ts_sa_currencies_data_01;
alter session set current_schema = SA_CURRENCIES_DATA;

drop table SA_T_CURRENCY;

CREATE TABLE SA_T_CURRENCY(
    CURRENCY_ID NUMBER,
    CURRENCY_NAME VARCHAR(20),
    CURRENCY_COUNTRY_CODE VARCHAR2(10),
    EXCHANGE_RATE  DECIMAL(5,2)
);

INSERT INTO SA_T_CURRENCY VALUES (1, 'BYN', 'BLR', 2.52 );
INSERT INTO SA_T_CURRENCY VALUES (2, 'UAH', 'UKR', 3.67 );
INSERT INTO SA_T_CURRENCY VALUES (3, 'PLN', 'POL', 4.61 );
INSERT INTO SA_T_CURRENCY VALUES (4, 'USD', 'USA', 1 );
INSERT INTO SA_T_CURRENCY VALUES (5, '', '', 1 );

select * from SA_T_CURRENCY;

SELECT COUNT(*) FROM SA_T_CURRENCY;

GRANT SELECT ON SA_T_CURRENCY TO SA_EXT_REF_DATA;
GRANT SELECT ON SA_T_CURRENCY TO SA_THEATER_DATA;
GRANT SELECT ON SA_T_CURRENCY TO DW_CL;