alter session set current_schema = DW_DATA;

-- DROP TABLE DIM_MOVIE;

CREATE TABLE DIM_MOVIE(
    MOVIE_ID            NUMBER NOT NULL,     
    MOVIE_NAME          VARCHAR2(50) NOT NULL,
    MOVIE_YEAR          VARCHAR2(4) NOT NULL,
    MOVIE_LEVEL1        VARCHAR2(50) NOT NULL,
    MOVIE_LEVEL2        VARCHAR2(50),
    MOVIE_LEVEL3        VARCHAR2(50),
    MOVIE_DURATION      NUMBER,
    CONSTRAINT "PK_T.DIM_MOVIE" PRIMARY KEY(MOVIE_ID) 
);

-- DROP SEQUENCE SEQ_MOVIE;
CREATE SEQUENCE SEQ_MOVIE
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
 select * from DIM_MOVIE;