alter session set current_schema = DW_DATA;

DROP TABLE DIM_THEATER;

CREATE TABLE DIM_THEATER(
    THEATER_ID NUMBER NOT NULL, 
    COUNTRY_CODE               VARCHAR2 (10) NOT NULL,
    CITY                       VARCHAR2 (50),
    THEATER_NAME               VARCHAR2(50) NOT NULL,
    THEATER_ADDRESS            VARCHAR2(100) NOT NULL,
    THEATER_PHONE              VARCHAR2(15),
    CONSTRAINT "PK_T.DIM_THEATER" PRIMARY KEY(THEATER_ID) 
);


 --DROP SEQUENCE SEQ_THEATERS;
CREATE SEQUENCE SEQ_THEATERS
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;

select * from DIM_THEATER;