alter session set current_schema = DW_DATA;
--DROP TABLE DIM_PROMOTION CASCADE CONSTRAINTS;

CREATE TABLE DIM_PROMOTION(
    PROMOTION_ID NUMBER NOT NULL, 
    PROMOTION_NUM NUMBER NOT NULL, 
    DISCOUNT DECIMAL(3,2),
    VALID_FROM DATE,
    VALID_TO DATE,
    IS_ACTIVE CHAR(1) CHECK (IS_ACTIVE IN ('Y','N')),
    CONSTRAINT "PK_T.DIM_PROMOTION" PRIMARY KEY(PROMOTION_ID) 
);

--DROP  SEQUENCE SEQ_PROMOTIONS;
CREATE SEQUENCE SEQ_PROMOTIONS
 START WITH     1
 INCREMENT BY   1
 NOCACHE
 NOCYCLE;
 
select * from  DIM_PROMOTION order by discount;