-- Storage level
CREATE USER SA_EXT_REF_DATA
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_ext_ref_data_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO SA_EXT_REF_DATA;

CREATE USER SA_CURRENCIES_DATA
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_currencies_data_01; 
GRANT CONNECT,CREATE VIEW,RESOURCE TO SA_CURRENCIES_DATA;

CREATE USER SA_THEATER_DATA
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_theater_data_01;  
GRANT CONNECT,CREATE VIEW,RESOURCE TO SA_THEATER_DATA;

CREATE USER SA_PROMOTION_DATA
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_promotion_data_01;   
GRANT CONNECT,CREATE VIEW,RESOURCE TO SA_PROMOTION_DATA;

CREATE USER SA_DATE_DATA
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_sa_date_data_01;   
GRANT CONNECT,CREATE VIEW,RESOURCE TO SA_DATE_DATA;

-- Data warehouse Cleansing Level
-- User: DW_CL
CREATE USER DW_CL
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_dw_cl_01;  
GRANT CONNECT,CREATE VIEW,RESOURCE TO DW_CL;
ALTER USER DW_CL quota unlimited on ts_dw_cl_01; 

-- Data warehouse Level
-- User: DW_DATA
CREATE USER DW_DATA
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_dw_data_01;
GRANT CONNECT,CREATE VIEW,RESOURCE TO DW_DATA;

-- Data warehouse Start Level and Data Marts
-- User: DM_ATTENDANCE
CREATE USER DM_ATTENDANCE
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_dm_attendance_01;  
GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_ATTENDANCE;

-- User: DM_MARKETING
CREATE USER DM_MARKETING
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_dm_marketing_01;  
GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_MARKETING;

-- User: DM_WORKLOAD
CREATE USER DM_WORKLOAD
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_dm_workload_01; 
GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_WORKLOAD;

-- User: DM_REVENUE
CREATE USER DM_REVENUE
  IDENTIFIED BY "%PWD%"
    DEFAULT TABLESPACE ts_dm_revenue_01; 
GRANT CONNECT,CREATE VIEW,RESOURCE TO DM_REVENUE;