ALTER USER SA_EXT_REF_DATA quota unlimited on ts_sa_ext_ref_data_01;
alter session set current_schema = SA_EXT_REF_DATA;

drop table SA_T_THEATERS;

CREATE TABLE SA_T_THEATERS(
    THEATER_ID NUMBER,  
    COUNTRY_CODE VARCHAR2 (10),
    CITY VARCHAR2 (50),
    THEATER_NAME VARCHAR2 (100),
    THEATER_ADDRESS VARCHAR2(100),
    THEATER_PHONE VARCHAR2(15)
);

SELECT COUNT(*) FROM SA_T_THEATERS;
SELECT * FROM SA_T_THEATERS;

GRANT SELECT ON SA_T_THEATERS TO DW_CL;

